### ISSUE TITLE
String Functions

### ISSUE THREAD

**Issue by gcds** [phpfunct/funct#2]
A list of string functions to implement for Version 0.1

- [x] string_between($string, $left, $right) (Extracts a string between $left and $right strings)
- [x] string_camelize
- [x] string_chomp_left($string, $prefix) (Removes $prefix from start of string)
- [x] string_chomp_right($string, $suffix) (Removes $suffix from end of string)
- [x] string_collapse_whitespace($string) (Converts all adjacent whitespace characters to a single space)
- [x] string_contains($string, $subString) (Returns true if the string contains $subString)
- [x] string_count ($string, $subString) (Returns the count of the number of occurrences of the $subString)
- [x] string_dasherize($string) (Returns a converted camel cased string into a string delimited by dashes)
- [x] string_ends_with($string) (Returns true if the string ends with $string)
- [x] string_include($string, $subString) (Returns true if the string contains the $subString)
- [x] string_is_alpha($string) (Return true if the string contains only letters)
- [x] string_is_alpha_numeric($string) (Return true if the string contains only letters and numbers)
- [x] string_is_lower
- [x] string_is_numeric($string) (Return true if the string only contains digits)
- [x] string_is_upper
- [x] string_latinise($string) (Removes accents from Latin characters)
- [x] string_left($string, $n) (Return the substring denoted by $n positive left-most characters)
- [x] string_lines($string) (Returns an array with the lines. Cross-platform compatible)
- [x] string_pad($string, $length, $char = ' ') (Pads the string in the center with specified character. $char may be a string or a number, defaults is a space)
- [x] string_pad_left($string, $length, $char = ' ') (Left pads the string)
- [x] string_pad_right($string, $length, $char = ' ') (Right pads the string)
- [x] string_repeat($string, $n) (Returns a string repeated $n times)
- [x] string_strip($string, $a, $b = null, $c = null) (Returns a new string with all occurrences of func_get_args()[1...])
- [x] string_right($string, $n) (Return the substring denoted by $n positive right-most characters)
- [x] string_slugify($string) (Converts the text into a valid url slug. Removes accents from Latin characters)
- [x] string_starts_with($string, $prefix) (Return true if the string starts with $prefix)
- [x] string_strip_punctuation($string) (Strip all of the punctuation)
- [x] string_times (Alias of string_repeat)
- [x] string_truncate($string, $length, $chars = '...') (Truncates the string, accounting for word placement and character count)
- [x] string_underscore($string) (Returns converted camel cased string into a string delimited by underscores)
- [x] string_titleize($string) (Creates a title version of the string. Capitalizes all the words and replaces some characters in the string to create a nicer looking title. string_titleize is meant for creating pretty output)
- [x] string_classify($string) (Converts string to camelized class name. First letter is always upper case)
- [x] string_to_sentence($array, $delimiter = ',', $lastDelimiter = '') (Join an array into a human readable sentence)
- [x] string_to_sentence_serial($array, $delimiter = ',', $lastDelimiter = '') (The same as string_to_sentence, but adjusts delimeters to use [Serial comma](http://en.wikipedia.org/wiki/Serial_comma))
- [x] string_lower_case_first
- [x] string_upper_case_first

**Comment by unxp** [comment]
Why create such functions like string_lower_case_first or string_upper_case_first? I don't say php names it's functions well, but i would prefer a library that provides additional functionality or shortcuts. Those functions I mentions just introduces another name to remember :)

**Comment by gcds** [comment]
Yes, I agree with you, but I also would like to help beginners to find functions faster than original ones :)

**Comment by unxp** [comment]
Write some comments on what listed functions should do, so others could understand what they should implement :)

**Comment by gcds** [comment]
Added :)

**Comment by gcds** [comment]
All functions realised
