### ISSUE TITLE
Proper slugify

### ISSUE THREAD

**Issue by aolko** [phpfunct/funct#20]
More languages, anyone? [...anyone?](https://github.com/cocur/slugify)

**Comment by gcds** [comment]
Hi, thanks for reaching, but this slugify is just plain slugify not for advance usage, but if you can write something better I am looking forward to integrating it. I just do not want to introduce 3rd party libraries.

**Comment by aolko** [comment]
just, please, add [more rules](https://github.com/cocur/slugify/tree/master/Resources/rules)

**Comment by gcds** [comment]
:+1: ok, I will add them later tomorrow maybe and will be released with 1.1.0 on Friday. But those rules will get not to slugiffier but to the latinizer :)
