### ISSUE TITLE
tests does not work on php7.1

### ISSUE THREAD

**Issue by mokevnin** [phpfunct/funct#44]
There was 1 error:

1) Funct\Tests\Collection\CollectionSizeTest::testCollectionSize with data set #3 (null, true, 0)
count(): Parameter must be an array or an object that implements Countable

/Users/mokevnin/mokevnin/funct/src/Collection.php:508
/Users/mokevnin/mokevnin/funct/src/Tests/Collection/CollectionSizeTest.php:34

--

There were 2 failures:

1) Funct\Tests\Strings\StringsIsLowerTest::testStringIsLower with data set #16 ('ąčęėįšųūž', false, true)
Failed asserting that false matches expected true.

/Users/mokevnin/mokevnin/funct/src/Tests/Strings/StringsIsLowerTest.php:52

2) Funct\Tests\Strings\StringsIsLowerTest::testStringIsLower with data set #18 ('ĄČĘĖĮŠŲŪŽ', false, true)
Failed asserting that false matches expected true.

/Users/mokevnin/mokevnin/funct/src/Tests/Strings/StringsIsLowerTest.php:52

**Comment by aurimasniekis** [comment]
Thank you for rising issue and PR 👍
